### ISSUE TITLE
Typo in recodext.h

### ISSUE THREAD

**Issue by rabenkind** [pinard/Recode#1]
Line 221 in src/recodext.h

should be:    bool ignore : 1;

it is:     bool ignore : 2;

Greetings Michael

**Comment by pinard** [comment]
Hi, Michael.

This is not a typo.  It once was ": 1" when I originally wrote it, but I had to change it to ": 2", somewhere between version 3.5c and 3.5d.  I think some compiler, which did not have "bool", forced Recode to declare an enum of 0 and 1 to replace bool, and that compiler then required a position to hold the sign bit (because the enum yielded the equivalent of an int instead of an unsigned).  I am not sure.

This has been reverted since then (commit a34df), on master.  You do not see it?  Maybe you are on some older branch or tag?

Have a good day!
